###Customer Sign up endpoint

POST http://localhost:3001/v1/user
Content-Type: application/json

{
     "name": "Shree Ram",
    "email": "millanadhikari@gmail.com",
    "password": "Manakamana123",
    "phone": "04212121212"
}

###Customer Sign In endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
         "email": "wedocleaning99@gmail.com",
    "password": "Manakamana123"
}

###Get a Customer profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphbnVrYUBnbWFpbC5jb20iLCJfaWQiOiI2MjE3NjY3NTRlNmQzNDE0NTVkMWYyOTMiLCJpYXQiOjE2NDU3MDA5MzgsImV4cCI6MTY0NTcwMTgzOH0.m02SaZSUs6zW3HZ61wJmV0WC0OIheI4K5fk-srBIlls


### Token routers

### Get refreshed tokens from
GET http://localhost:3001/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbGFuckBnbWFpbC5jb20iLCJpYXQiOjE2NDU2MTM3NTcsImV4cCI6MTY0NzM0MTc1N30.feTku4lY0MXa2w-PEjxBPT8q0Aa5rqUwBqKGUPT-GuY

      
###Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":  "millanadhikari@gmail.com"
}

      
###Password reset endpoints
PATCH http://localhost:3001/v1/user/reset-password
Content-Type: application/json

{
    "email":  "milanR@gmail.com",
    "pin": "434119",
    "newPassword":"Birtamode123"

}

###User Logout Endpoint   
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pbGFuckBnbWFpbC5jb20iLCJfaWQiOiI2MjE2MGQ5ZGFmNGZlYTU1ODZlODE0MzMiLCJpYXQiOjE2NDU2MTQyNDEsImV4cCI6MTY0NTYxNTE0MX0.SeHuDiejDZvey7RNgByWeIhYljrfkZ0fCr1mqlZWufg
